export type Element =
  | "Normal"
  | "Grass"
  | "Fire"
  | "Water"
  | "Electric"
  | "Bug"
  | "Flying"
  | "Poison"
  | "Ground"
  | "Rock"
  | "Psychic"
  | "Ice"
  | "Ghost"
  | "Dragon"
  | "Dark"
  | "Steel"
  | "Fairy"
  | "Fighting";
export type Move = {
  name: string;
  type: Element;
  power: number;
  accuracy: number;
  kind?: "heal" | "guard" | "poison" | "sleep";
  pp: number;
};
export const MOVES: Record<string, Move> = {
  tackle: { name: "Tackle", type: "Normal", power: 40, accuracy: 100, pp: 35 },
  quick: {
    name: "Quick Attack",
    type: "Normal",
    power: 45,
    accuracy: 100,
    pp: 30,
  },
  bite: { name: "Bite", type: "Dark", power: 60, accuracy: 100, pp: 25 },
  swift: { name: "Swift", type: "Normal", power: 65, accuracy: 100, pp: 20 },
  vine: { name: "Vine Whip", type: "Grass", power: 45, accuracy: 100, pp: 25 },
  leaf: { name: "Razor Leaf", type: "Grass", power: 65, accuracy: 95, pp: 25 },
  solar: {
    name: "Solar Beam",
    type: "Grass",
    power: 105,
    accuracy: 90,
    pp: 10,
  },
  ember: { name: "Ember", type: "Fire", power: 45, accuracy: 100, pp: 25 },
  flame: {
    name: "Flamethrower",
    type: "Fire",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  bubble: { name: "Bubble", type: "Water", power: 45, accuracy: 100, pp: 25 },
  water: {
    name: "Water Pulse",
    type: "Water",
    power: 65,
    accuracy: 100,
    pp: 20,
  },
  surf: { name: "Surf", type: "Water", power: 90, accuracy: 100, pp: 15 },
  spark: {
    name: "Thunder Shock",
    type: "Electric",
    power: 45,
    accuracy: 100,
    pp: 30,
  },
  bolt: {
    name: "Thunderbolt",
    type: "Electric",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  bug: { name: "Bug Bite", type: "Bug", power: 55, accuracy: 100, pp: 25 },
  web: { name: "Pin Missile", type: "Bug", power: 70, accuracy: 95, pp: 20 },
  gust: { name: "Gust", type: "Flying", power: 45, accuracy: 100, pp: 30 },
  air: { name: "Air Slash", type: "Flying", power: 80, accuracy: 95, pp: 15 },
  poison: {
    name: "Poison Sting",
    type: "Poison",
    power: 30,
    accuracy: 100,
    kind: "poison",
    pp: 25,
  },
  sludge: {
    name: "Sludge Bomb",
    type: "Poison",
    power: 85,
    accuracy: 95,
    kind: "poison",
    pp: 10,
  },
  mud: { name: "Mud Shot", type: "Ground", power: 55, accuracy: 95, pp: 20 },
  quake: {
    name: "Earthquake",
    type: "Ground",
    power: 95,
    accuracy: 100,
    pp: 10,
  },
  rock: { name: "Rock Throw", type: "Rock", power: 55, accuracy: 90, pp: 25 },
  stone: { name: "Rock Slide", type: "Rock", power: 80, accuracy: 90, pp: 15 },
  confusion: {
    name: "Confusion",
    type: "Psychic",
    power: 50,
    accuracy: 100,
    pp: 25,
  },
  psychic: {
    name: "Psychic",
    type: "Psychic",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  ice: { name: "Ice Shard", type: "Ice", power: 45, accuracy: 100, pp: 25 },
  blizzard: { name: "Ice Beam", type: "Ice", power: 90, accuracy: 100, pp: 15 },
  lick: { name: "Lick", type: "Ghost", power: 40, accuracy: 100, pp: 30 },
  shadow: {
    name: "Shadow Ball",
    type: "Ghost",
    power: 85,
    accuracy: 100,
    pp: 15,
  },
  dragon: {
    name: "Dragon Breath",
    type: "Dragon",
    power: 60,
    accuracy: 100,
    pp: 20,
  },
  claw: {
    name: "Dragon Claw",
    type: "Dragon",
    power: 85,
    accuracy: 100,
    pp: 15,
  },
  dark: { name: "Dark Pulse", type: "Dark", power: 85, accuracy: 100, pp: 15 },
  metal: { name: "Metal Claw", type: "Steel", power: 55, accuracy: 95, pp: 25 },
  iron: { name: "Iron Head", type: "Steel", power: 85, accuracy: 100, pp: 15 },
  fairy: {
    name: "Fairy Wind",
    type: "Fairy",
    power: 45,
    accuracy: 100,
    pp: 25,
  },
  moon: { name: "Moonblast", type: "Fairy", power: 90, accuracy: 100, pp: 15 },
  kick: {
    name: "Low Kick",
    type: "Fighting",
    power: 55,
    accuracy: 100,
    pp: 25,
  },
  punch: {
    name: "Drain Punch",
    type: "Fighting",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  heal: {
    name: "Recover",
    type: "Normal",
    power: 0,
    accuracy: 100,
    kind: "heal",
    pp: 5,
  },
  guard: {
    name: "Protect",
    type: "Normal",
    power: 0,
    accuracy: 100,
    kind: "guard",
    pp: 10,
  },
  sleep: {
    name: "Sleep Powder",
    type: "Grass",
    power: 0,
    accuracy: 75,
    kind: "sleep",
    pp: 10,
  },
};
export interface Species {
  id: number;
  name: string;
  type: Element;
  secondary?: Element;
  hp: number;
  atk: number;
  def: number;
  speed: number;
  moves: string[];
  evolve?: [number, number];
  rarity: number;
  desc: string;
}
const rows: [
  number,
  string,
  Element,
  number,
  number,
  number,
  number,
  string[],
  number,
  number?,
  number?,
][] = [
  [
    1,
    "Bulbasaur",
    "Grass",
    45,
    49,
    49,
    45,
    ["tackle", "vine", "leaf", "sleep", "solar"],
    1,
    16,
    2,
  ],
  [
    2,
    "Ivysaur",
    "Grass",
    60,
    62,
    63,
    60,
    ["tackle", "vine", "leaf", "sleep", "solar"],
    2,
    32,
    3,
  ],
  [
    3,
    "Venusaur",
    "Grass",
    80,
    82,
    83,
    80,
    ["vine", "leaf", "sleep", "solar"],
    4,
  ],
  [
    4,
    "Charmander",
    "Fire",
    39,
    52,
    43,
    65,
    ["tackle", "ember", "bite", "flame"],
    1,
    16,
    5,
  ],
  [
    5,
    "Charmeleon",
    "Fire",
    58,
    64,
    58,
    80,
    ["ember", "bite", "claw", "flame"],
    2,
    36,
    6,
  ],
  [
    6,
    "Charizard",
    "Fire",
    78,
    84,
    78,
    100,
    ["flame", "air", "claw", "guard"],
    4,
  ],
  [
    7,
    "Squirtle",
    "Water",
    44,
    48,
    65,
    43,
    ["tackle", "bubble", "bite", "water", "surf"],
    1,
    16,
    8,
  ],
  [
    8,
    "Wartortle",
    "Water",
    59,
    63,
    80,
    58,
    ["bubble", "bite", "water", "surf"],
    2,
    36,
    9,
  ],
  [
    9,
    "Blastoise",
    "Water",
    79,
    83,
    100,
    78,
    ["water", "bite", "surf", "guard"],
    4,
  ],
  [10, "Caterpie", "Bug", 45, 30, 35, 45, ["tackle", "bug"], 1, 7, 11],
  [11, "Metapod", "Bug", 50, 20, 55, 30, ["tackle", "guard", "bug"], 1, 10, 12],
  [
    12,
    "Butterfree",
    "Bug",
    60,
    80,
    50,
    70,
    ["gust", "confusion", "sleep", "web"],
    2,
  ],
  [13, "Weedle", "Bug", 40, 35, 30, 50, ["poison", "bug"], 1, 7, 14],
  [14, "Kakuna", "Bug", 45, 25, 50, 35, ["poison", "guard"], 1, 10, 15],
  [
    15,
    "Beedrill",
    "Bug",
    65,
    90,
    40,
    75,
    ["poison", "web", "air", "sludge"],
    2,
  ],
  [
    16,
    "Pidgey",
    "Flying",
    40,
    45,
    40,
    56,
    ["tackle", "gust", "quick", "air"],
    1,
    18,
    17,
  ],
  [
    17,
    "Pidgeotto",
    "Flying",
    63,
    60,
    55,
    71,
    ["gust", "quick", "air", "swift"],
    2,
    36,
    18,
  ],
  [
    18,
    "Pidgeot",
    "Flying",
    83,
    80,
    75,
    101,
    ["quick", "air", "swift", "guard"],
    3,
  ],
  [
    19,
    "Rattata",
    "Normal",
    30,
    56,
    35,
    72,
    ["tackle", "quick", "bite", "swift"],
    1,
    20,
    20,
  ],
  [
    20,
    "Raticate",
    "Normal",
    55,
    81,
    60,
    97,
    ["quick", "bite", "swift", "dark"],
    2,
  ],
  [
    25,
    "Pikachu",
    "Electric",
    35,
    55,
    40,
    90,
    ["quick", "spark", "swift", "bolt"],
    2,
    28,
    26,
  ],
  [
    26,
    "Raichu",
    "Electric",
    60,
    90,
    55,
    110,
    ["spark", "swift", "bolt", "guard"],
    3,
  ],
  [
    27,
    "Sandshrew",
    "Ground",
    50,
    75,
    85,
    40,
    ["tackle", "mud", "rock", "quake"],
    1,
    22,
    28,
  ],
  [
    28,
    "Sandslash",
    "Ground",
    75,
    100,
    110,
    65,
    ["mud", "rock", "quake", "metal"],
    3,
  ],
  [
    35,
    "Clefairy",
    "Fairy",
    70,
    45,
    48,
    35,
    ["tackle", "fairy", "heal", "moon"],
    2,
    26,
    36,
  ],
  [
    36,
    "Clefable",
    "Fairy",
    95,
    70,
    73,
    60,
    ["fairy", "heal", "moon", "psychic"],
    3,
  ],
  [
    37,
    "Vulpix",
    "Fire",
    38,
    41,
    40,
    65,
    ["quick", "ember", "bite", "flame"],
    2,
    28,
    38,
  ],
  [
    38,
    "Ninetales",
    "Fire",
    73,
    76,
    75,
    100,
    ["flame", "confusion", "dark", "guard"],
    4,
  ],
  [
    39,
    "Jigglypuff",
    "Fairy",
    115,
    45,
    20,
    20,
    ["tackle", "fairy", "sleep", "moon"],
    2,
    25,
    40,
  ],
  [
    40,
    "Wigglytuff",
    "Fairy",
    140,
    70,
    45,
    45,
    ["fairy", "sleep", "moon", "swift"],
    3,
  ],
  [
    41,
    "Zubat",
    "Poison",
    40,
    45,
    35,
    55,
    ["bite", "poison", "gust", "air"],
    1,
    22,
    42,
  ],
  [
    42,
    "Golbat",
    "Poison",
    75,
    80,
    70,
    90,
    ["bite", "sludge", "air", "dark"],
    3,
  ],
  [
    43,
    "Oddish",
    "Grass",
    45,
    50,
    55,
    30,
    ["vine", "poison", "sleep", "leaf"],
    1,
    21,
    44,
  ],
  [
    44,
    "Gloom",
    "Grass",
    60,
    65,
    70,
    40,
    ["poison", "sleep", "leaf", "sludge"],
    2,
    32,
    45,
  ],
  [
    45,
    "Vileplume",
    "Grass",
    75,
    80,
    85,
    50,
    ["sleep", "leaf", "sludge", "solar"],
    3,
  ],
  [
    50,
    "Diglett",
    "Ground",
    10,
    55,
    25,
    95,
    ["tackle", "mud", "rock", "quake"],
    1,
    26,
    51,
  ],
  [
    51,
    "Dugtrio",
    "Ground",
    35,
    100,
    50,
    120,
    ["mud", "rock", "quake", "bite"],
    3,
  ],
  [
    52,
    "Meowth",
    "Normal",
    40,
    45,
    35,
    90,
    ["tackle", "bite", "quick", "swift"],
    2,
    28,
    53,
  ],
  [
    53,
    "Persian",
    "Normal",
    65,
    70,
    60,
    115,
    ["bite", "quick", "swift", "dark"],
    3,
  ],
  [
    54,
    "Psyduck",
    "Water",
    50,
    52,
    48,
    55,
    ["tackle", "bubble", "confusion", "water", "psychic"],
    1,
    33,
    55,
  ],
  [
    55,
    "Golduck",
    "Water",
    80,
    82,
    78,
    85,
    ["water", "confusion", "surf", "psychic"],
    3,
  ],
  [
    58,
    "Growlithe",
    "Fire",
    55,
    70,
    45,
    60,
    ["bite", "ember", "quick", "flame"],
    2,
    32,
    59,
  ],
  [
    59,
    "Arcanine",
    "Fire",
    90,
    110,
    80,
    95,
    ["bite", "flame", "swift", "claw"],
    4,
  ],
  [
    60,
    "Poliwag",
    "Water",
    40,
    50,
    40,
    90,
    ["bubble", "tackle", "water", "punch"],
    1,
    25,
    61,
  ],
  [
    61,
    "Poliwhirl",
    "Water",
    65,
    65,
    65,
    90,
    ["water", "kick", "surf", "punch"],
    2,
    36,
    62,
  ],
  [
    62,
    "Poliwrath",
    "Water",
    90,
    95,
    95,
    70,
    ["surf", "punch", "blizzard", "guard"],
    4,
  ],
  [
    63,
    "Abra",
    "Psychic",
    25,
    65,
    15,
    90,
    ["confusion", "guard", "psychic", "heal"],
    2,
    16,
    64,
  ],
  [
    64,
    "Kadabra",
    "Psychic",
    40,
    85,
    30,
    105,
    ["confusion", "guard", "psychic", "heal"],
    3,
    36,
    65,
  ],
  [
    65,
    "Alakazam",
    "Psychic",
    55,
    110,
    45,
    120,
    ["psychic", "heal", "shadow", "guard"],
    4,
  ],
  [
    66,
    "Machop",
    "Fighting",
    70,
    80,
    50,
    35,
    ["tackle", "kick", "rock", "punch"],
    1,
    28,
    67,
  ],
  [
    67,
    "Machoke",
    "Fighting",
    80,
    100,
    70,
    45,
    ["kick", "rock", "punch", "guard"],
    2,
    40,
    68,
  ],
  [
    68,
    "Machamp",
    "Fighting",
    90,
    130,
    80,
    55,
    ["punch", "stone", "quake", "guard"],
    4,
  ],
  [
    74,
    "Geodude",
    "Rock",
    40,
    80,
    100,
    20,
    ["tackle", "rock", "mud", "stone"],
    1,
    25,
    75,
  ],
  [
    75,
    "Graveler",
    "Rock",
    55,
    95,
    115,
    35,
    ["rock", "mud", "stone", "quake"],
    2,
    38,
    76,
  ],
  [
    76,
    "Golem",
    "Rock",
    80,
    120,
    130,
    45,
    ["stone", "quake", "guard", "punch"],
    4,
  ],
  [
    77,
    "Ponyta",
    "Fire",
    50,
    85,
    55,
    90,
    ["tackle", "ember", "quick", "flame"],
    2,
    40,
    78,
  ],
  [
    78,
    "Rapidash",
    "Fire",
    65,
    100,
    70,
    105,
    ["flame", "quick", "bite", "guard"],
    4,
  ],
  [
    79,
    "Slowpoke",
    "Water",
    90,
    65,
    65,
    15,
    ["tackle", "water", "confusion", "heal"],
    1,
    37,
    80,
  ],
  [
    80,
    "Slowbro",
    "Water",
    95,
    75,
    110,
    30,
    ["surf", "psychic", "heal", "blizzard"],
    3,
  ],
  [
    81,
    "Magnemite",
    "Electric",
    25,
    60,
    70,
    45,
    ["tackle", "spark", "metal", "bolt"],
    2,
    30,
    82,
  ],
  [
    82,
    "Magneton",
    "Electric",
    50,
    95,
    95,
    70,
    ["spark", "metal", "bolt", "iron"],
    3,
  ],
  [
    86,
    "Seel",
    "Ice",
    65,
    45,
    55,
    45,
    ["tackle", "ice", "water", "blizzard"],
    1,
    34,
    87,
  ],
  [
    87,
    "Dewgong",
    "Ice",
    90,
    70,
    80,
    70,
    ["water", "ice", "surf", "blizzard"],
    3,
  ],
  [
    92,
    "Gastly",
    "Ghost",
    30,
    65,
    30,
    80,
    ["lick", "confusion", "poison", "shadow"],
    2,
    25,
    93,
  ],
  [
    93,
    "Haunter",
    "Ghost",
    45,
    85,
    45,
    95,
    ["lick", "poison", "shadow", "dark"],
    3,
    38,
    94,
  ],
  [
    94,
    "Gengar",
    "Ghost",
    60,
    110,
    60,
    110,
    ["shadow", "sludge", "dark", "psychic"],
    4,
  ],
  [95, "Onix", "Rock", 35, 45, 160, 70, ["rock", "mud", "stone", "iron"], 3],
  [
    104,
    "Cubone",
    "Ground",
    50,
    50,
    95,
    35,
    ["tackle", "mud", "bite", "quake"],
    2,
    28,
    105,
  ],
  [
    105,
    "Marowak",
    "Ground",
    60,
    80,
    110,
    45,
    ["mud", "bite", "quake", "stone"],
    3,
  ],
  [
    113,
    "Chansey",
    "Normal",
    150,
    35,
    35,
    50,
    ["tackle", "fairy", "heal", "swift"],
    4,
  ],
  [
    114,
    "Tangela",
    "Grass",
    65,
    75,
    115,
    60,
    ["vine", "sleep", "leaf", "solar"],
    3,
  ],
  [123, "Scyther", "Bug", 70, 110, 80, 105, ["quick", "bug", "air", "web"], 4],
  [
    124,
    "Jynx",
    "Ice",
    65,
    90,
    35,
    95,
    ["ice", "confusion", "blizzard", "psychic"],
    3,
  ],
  [
    125,
    "Electabuzz",
    "Electric",
    65,
    83,
    57,
    105,
    ["spark", "kick", "bolt", "punch"],
    3,
  ],
  [
    126,
    "Magmar",
    "Fire",
    65,
    95,
    57,
    93,
    ["ember", "punch", "flame", "sludge"],
    3,
  ],
  [129, "Magikarp", "Water", 20, 20, 55, 80, ["tackle", "bubble"], 1, 20, 130],
  [
    130,
    "Gyarados",
    "Water",
    95,
    125,
    79,
    81,
    ["bite", "water", "dragon", "surf"],
    4,
  ],
  [
    131,
    "Lapras",
    "Ice",
    130,
    85,
    80,
    60,
    ["water", "ice", "surf", "blizzard"],
    4,
  ],
  [
    133,
    "Eevee",
    "Normal",
    55,
    55,
    50,
    55,
    ["tackle", "quick", "bite", "swift"],
    3,
    30,
    134,
  ],
  [
    134,
    "Vaporeon",
    "Water",
    130,
    85,
    60,
    65,
    ["water", "bite", "surf", "heal"],
    4,
  ],
  [
    135,
    "Jolteon",
    "Electric",
    65,
    90,
    60,
    130,
    ["spark", "quick", "bolt", "web"],
    4,
  ],
  [
    136,
    "Flareon",
    "Fire",
    65,
    130,
    60,
    65,
    ["ember", "bite", "flame", "swift"],
    4,
  ],
  [
    143,
    "Snorlax",
    "Normal",
    160,
    110,
    65,
    30,
    ["tackle", "bite", "heal", "quake"],
    4,
  ],
  [
    147,
    "Dratini",
    "Dragon",
    41,
    64,
    45,
    50,
    ["tackle", "dragon", "water", "claw"],
    3,
    30,
    148,
  ],
  [
    148,
    "Dragonair",
    "Dragon",
    61,
    84,
    65,
    70,
    ["dragon", "water", "claw", "bolt"],
    4,
    45,
    149,
  ],
  [
    149,
    "Dragonite",
    "Dragon",
    91,
    134,
    95,
    80,
    ["claw", "air", "bolt", "surf"],
    5,
  ],
  [
    151,
    "Mew",
    "Psychic",
    100,
    100,
    100,
    100,
    ["psychic", "moon", "heal", "shadow"],
    5,
  ],
];
export const SPECIES: Record<number, Species> = Object.fromEntries(
  rows.map(([id, name, type, hp, atk, def, speed, moves, rarity, lv, next]) => [
    id,
    {
      id,
      name,
      type,
      hp,
      atk,
      def,
      speed,
      moves,
      rarity,
      evolve: lv ? [lv, next!] : undefined,
      desc: `${name} thrives in Aurelian's ${type === "Water" ? "rivers and quiet shores" : type === "Fire" ? "sunlit ridges" : type === "Ghost" ? "ancient, forgotten places" : type === "Ice" ? "snow-covered highlands" : "wild landscapes"}. Patient explorers may earn its trust.`,
    },
  ]),
);
export const COLORS: Record<Element, string> = {
  Normal: "#919580",
  Grass: "#699b50",
  Fire: "#d57847",
  Water: "#589bb7",
  Electric: "#c9a638",
  Bug: "#8d9d48",
  Flying: "#8e9ebe",
  Poison: "#a178a3",
  Ground: "#b39b69",
  Rock: "#9e946e",
  Psychic: "#c27b99",
  Ice: "#71afb1",
  Ghost: "#827fa4",
  Dragon: "#757fab",
  Dark: "#746b66",
  Steel: "#819b98",
  Fairy: "#c993b3",
  Fighting: "#b0775e",
};
export const ADVANTAGES: Partial<Record<Element, Element[]>> = {
  Fire: ["Grass", "Bug", "Ice", "Steel"],
  Water: ["Fire", "Ground", "Rock"],
  Grass: ["Water", "Ground", "Rock"],
  Electric: ["Water", "Flying"],
  Bug: ["Grass", "Psychic", "Dark"],
  Flying: ["Grass", "Bug", "Fighting"],
  Poison: ["Grass", "Fairy"],
  Ground: ["Fire", "Electric", "Poison", "Rock", "Steel"],
  Rock: ["Fire", "Ice", "Flying", "Bug"],
  Psychic: ["Fighting", "Poison"],
  Ice: ["Grass", "Ground", "Flying", "Dragon"],
  Ghost: ["Psychic", "Ghost"],
  Dragon: ["Dragon"],
  Dark: ["Psychic", "Ghost"],
  Steel: ["Ice", "Rock", "Fairy"],
  Fairy: ["Fighting", "Dragon", "Dark"],
  Fighting: ["Normal", "Rock", "Steel", "Ice", "Dark"],
};
export const RESISTANCES: Partial<Record<Element, Element[]>> = {
  Fire: ["Fire", "Water", "Rock", "Dragon"],
  Water: ["Water", "Grass", "Dragon"],
  Grass: ["Fire", "Grass", "Poison", "Flying", "Bug", "Dragon", "Steel"],
  Electric: ["Electric", "Grass", "Dragon"],
  Normal: ["Rock", "Steel"],
  Ice: ["Fire", "Water", "Ice", "Steel"],
  Ghost: ["Dark"],
  Dragon: ["Steel"],
  Psychic: ["Psychic", "Steel"],
  Fighting: ["Poison", "Flying", "Psychic", "Bug", "Fairy"],
  Poison: ["Poison", "Ground", "Rock", "Ghost"],
  Ground: ["Grass", "Bug"],
  Flying: ["Electric", "Rock", "Steel"],
  Bug: ["Fire", "Fighting", "Poison", "Flying", "Ghost", "Steel", "Fairy"],
  Rock: ["Fighting", "Ground", "Steel"],
  Dark: ["Fighting", "Dark", "Fairy"],
  Steel: ["Fire", "Water", "Electric", "Steel"],
  Fairy: ["Fire", "Poison", "Steel"],
};
export const IMMUNITIES: Partial<Record<Element, Element[]>> = {
  Normal: ["Ghost"],
  Fighting: ["Ghost"],
  Ghost: ["Normal"],
  Electric: ["Ground"],
  Ground: ["Flying"],
  Psychic: ["Dark"],
  Poison: ["Steel"],
  Dragon: ["Fairy"],
};
export const REGIONS = [
  {
    name: "Verdant Hollow",
    subtitle: "A little place. A big beginning.",
    biome: "meadow",
    color: "#739454",
    level: 3,
    pool: [16, 19, 10, 43, 25, 133],
    description:
      "Home smells like fresh bread and rain. Beyond the old gate, the whole world is waiting.",
  },
  {
    name: "Whispering Woods",
    subtitle: "Follow the fireflies",
    biome: "forest",
    color: "#4d7961",
    level: 6,
    pool: [10, 13, 43, 25, 16, 63, 123, 1],
    description:
      "An ancient forest that remembers every footstep. Something is calling from beneath its roots.",
  },
  {
    name: "Amber Coast",
    subtitle: "Where the sun meets the sea",
    biome: "coast",
    color: "#c09c64",
    level: 11,
    pool: [54, 60, 129, 79, 7, 133, 52],
    description:
      "Tide pools, salt-worn cabins, and a lighthouse that has been dark for a hundred years.",
  },
  {
    name: "Sunstone Mesa",
    subtitle: "A heart beneath the stone",
    biome: "desert",
    color: "#b77e52",
    level: 16,
    pool: [27, 50, 74, 77, 104, 95],
    description:
      "Wind carries miners’ songs through red-rock canyons. The mountain is still listening.",
  },
  {
    name: "Emberfall",
    subtitle: "Not every flame destroys",
    biome: "autumn",
    color: "#b7794f",
    level: 22,
    pool: [37, 58, 77, 4, 126, 133, 136],
    description:
      "Copper leaves glow beneath a sleeping volcano. A village is learning to trust the fire again.",
  },
  {
    name: "Moonveil Marsh",
    subtitle: "The things we leave behind",
    biome: "marsh",
    color: "#7a7897",
    level: 28,
    pool: [92, 41, 35, 39, 114, 63],
    description:
      "Lost lanterns drift across violet water. Here, even old regrets take on a life of their own.",
  },
  {
    name: "Frostpeak",
    subtitle: "Find warmth in the wilderness",
    biome: "snow",
    color: "#87a9aa",
    level: 34,
    pool: [86, 124, 131, 66, 81, 113],
    description:
      "An observatory above the clouds, and a promise buried beneath the snow.",
  },
  {
    name: "Stormhaven",
    subtitle: "After every storm",
    biome: "storm",
    color: "#6c8e94",
    level: 40,
    pool: [81, 125, 25, 147, 123, 143, 135],
    description:
      "Wild lightning powers a city of inventors. Their greatest invention has gone silent.",
  },
  {
    name: "Aurelian Summit",
    subtitle: "Every light begins with you",
    biome: "summit",
    color: "#919669",
    level: 46,
    pool: [147, 133, 35, 63, 143, 151],
    description:
      "Eight paths lead here. Eight stories become one. The last beacon waits for its keeper.",
  },
];
export const CHAPTERS = [
  {
    title: "A whisper in the woods",
    region: 1,
    keeper: "Rowan",
    boss: 12,
    intro:
      "The beacons used to sing to each other. Now the forest has fallen quiet. Professor Fern believes the Pokémon know why. Find Ivy in the woods — and listen.",
    reveal:
      "Rowan rests a hand on the stone. “The beacon isn’t broken. It’s afraid.” Your partner steps closer, and the first light returns. A folded letter falls from the roots: Project Stillwater. — F.",
    bossLine:
      "The forest protects those who protect it. Show me the bond you share.",
  },
  {
    title: "Letters to the tide",
    region: 2,
    keeper: "Marina",
    boss: 130,
    intro:
      "The letter points to Amber Coast. Lighthouse keeper Marina has been collecting messages that wash ashore. One carries your mother’s handwriting.",
    reveal:
      "“Your mother sailed inland, against the tide,” Marina says. Her letter reads: We built the beacons to share energy. Director Vale is making them take it. Find me at the summit.",
    bossLine:
      "A strong current is nothing without a shore to return to. Let me see your anchor.",
  },
  {
    title: "The mountain remembers",
    region: 3,
    keeper: "Flint",
    boss: 76,
    intro:
      "Sunstone’s mines have gone silent. The miners blame wild Pokémon, but Ivy has found machines buried beside the beacon. Help Flint uncover the truth.",
    reveal:
      "The machine bears the Stillwater seal. Flint breaks its power cell. “Vale promised us clean energy. He never mentioned who would pay for it.” Deep in the mountain, a heartbeat returns.",
    bossLine: "Trust is built one stone at a time. Show me what you stand for.",
  },
  {
    title: "A brighter kind of fire",
    region: 4,
    keeper: "Cinder",
    boss: 59,
    intro:
      "Emberfall’s Pokémon are fleeing their homes. Cinder is sheltering them, but the town wants to extinguish the beacon forever. Earn their trust before fear wins.",
    reveal:
      "Cinder opens the sanctuary gates. Pokémon and townspeople gather in the warm light. Ivy grins. “Maybe being a trainer means helping people understand what they’re afraid of.”",
    bossLine:
      "Power can shelter or destroy. What will you choose to do with yours?",
  },
  {
    title: "Echoes of yesterday",
    region: 5,
    keeper: "Luna",
    boss: 94,
    intro:
      "A voice calls from Moonveil. The marsh remembers a younger Vale — a scientist who lost his partner Pokémon in a storm. Find the memory he tried to bury.",
    reveal:
      "The lantern shows Vale cradling an empty Poké Ball. “If nothing ever changes, nothing can be lost.” Luna closes her eyes. “He wants to freeze the world in a perfect moment.”",
    bossLine:
      "You cannot carry every sorrow. But you can choose what grows from it.",
  },
  {
    title: "The long way home",
    region: 6,
    keeper: "Aspen",
    boss: 131,
    intro:
      "The observatory holds your mother’s final transmission. Aspen has kept it safe through the longest winter. Reach the beacon and learn why she never came home.",
    reveal:
      "Your mother’s voice crackles through the radio. “I’m holding the summit open. Don’t come because you have to. Come because this world is worth a little uncertainty. I love you.”",
    bossLine:
      "The mountain asks for patience, courage, and someone to walk beside you.",
  },
  {
    title: "Weathering the storm",
    region: 7,
    keeper: "Volt",
    boss: 135,
    intro:
      "Stillwater is drawing its final charge from Stormhaven. Ivy has rallied the keepers. Free the city’s beacon before Vale closes the path to the summit.",
    reveal:
      "Seven beams cut through the clouds. Ivy grips your shoulder. “When we left home, I wanted to be the strongest. Now I just want there to be a world worth exploring. Let’s bring her home.”",
    bossLine:
      "You’ve brought us this far. Give me everything you have — then give the world a future.",
  },
  {
    title: "A world worth wandering",
    region: 8,
    keeper: "Director Vale",
    boss: 149,
    intro:
      "At the summit, the sky has stopped moving. Your mother is inside the last beacon. Vale offers a world without loss. Your partner looks at you. The choice has always been yours.",
    reveal:
      "“I thought keeping everything still would make it stay,” Vale whispers. Your partner nudges his hand. The sky moves. Your mother steps into the sunrise. The world isn’t perfect. It is alive. And your adventure is only beginning.",
    bossLine:
      "I can spare everyone the pain of goodbye. Why would you choose a world that changes?",
  },
];
export const SIDE_QUESTS = [
  {
    id: "collector",
    name: "A pocketful of possibilities",
    desc: "Register 12 different Pokémon in your Pokédex.",
    target: 12,
    reward: 1800,
    kind: "caught",
  },
  {
    id: "naturalist",
    name: "Aurelian field guide",
    desc: "Register 30 different Pokémon.",
    target: 30,
    reward: 4500,
    kind: "caught",
  },
  {
    id: "masterdex",
    name: "A lifetime of discovery",
    desc: "Register 60 different Pokémon.",
    target: 60,
    reward: 10000,
    kind: "caught",
  },
  {
    id: "walker",
    name: "The scenic route",
    desc: "Walk 2,000 steps through Aurelian.",
    target: 2000,
    reward: 1200,
    kind: "steps",
  },
  {
    id: "wanderer",
    name: "Leave no path unexplored",
    desc: "Visit every region.",
    target: 9,
    reward: 3000,
    kind: "visited",
  },
  {
    id: "treasure",
    name: "Someone’s forgotten treasure",
    desc: "Find 12 supply chests hidden in the wild.",
    target: 12,
    reward: 2500,
    kind: "chests",
  },
  {
    id: "battler",
    name: "A friendly rivalry",
    desc: "Win 20 trainer battles.",
    target: 20,
    reward: 4000,
    kind: "trainers",
  },
  {
    id: "veteran",
    name: "The long road to mastery",
    desc: "Win 50 battles of any kind.",
    target: 50,
    reward: 5000,
    kind: "wins",
  },
];
export const ITEMS = {
  ball: {
    name: "Poké Ball",
    price: 180,
    description: "A familiar beginning for a new friendship.",
  },
  great: {
    name: "Great Ball",
    price: 450,
    description: "A more reliable ball for elusive Pokémon.",
  },
  potion: {
    name: "Potion",
    price: 120,
    description: "Restores 30 HP to one Pokémon.",
  },
  super: {
    name: "Super Potion",
    price: 350,
    description: "Restores 80 HP to one Pokémon.",
  },
  revive: {
    name: "Revive",
    price: 650,
    description: "Revives a fainted Pokémon with half its HP.",
  },
  ether: {
    name: "Ether",
    price: 250,
    description: "Restores all move PP to one Pokémon.",
  },
};
export type ItemId = keyof typeof ITEMS;
export const sprite = (id: number) => `/sprites/${id}.png`;
